# Generated by Django 2.0.5 on 2018-06-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('idAtributo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePerfil',
            fields=[
                ('idDetallePerfil', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('idNivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('idAtributo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel', to='simulacion.Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('voto', models.IntegerField(default=0)),
                ('media', models.ImageField(blank=True, upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('idSimulacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=75, null=True)),
                ('nombreEncuesta', models.CharField(max_length=75, null=True)),
                ('preguntaEncuesta', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulacionEstado',
            fields=[
                ('idSimulacionEstado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='simulacion',
            name='idSimulacionEstado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulacion.SimulacionEstado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idSimulacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='simulacion.Simulacion'),
        ),
        migrations.AddField(
            model_name='detalleperfil',
            name='idNivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalleperfil', to='simulacion.Nivel'),
        ),
        migrations.AddField(
            model_name='detalleperfil',
            name='idPerfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalleperfil', to='simulacion.Perfil'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='idSimulacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulacion.Simulacion'),
        ),
    ]
